### ISSUE TITLE
getting an error like this, i am open to give additional neccesary information if you still bother to maintain the program

### ISSUE THREAD

**Issue by muhalikin** [ferferga/WhatsAppMigrationTools#2]
![image](https://user-images.githubusercontent.com/40883042/204114520-028b1646-41cc-471b-b13a-c24c542080ff.png)

**Comment by ferferga** [comment]
The problem is clear, the file is not a database (probably because it's encrypted). I assume so as the folder you gave to the program is the same OneDrive directory that I remember that WhatsApp used for backups.

Read the docs.
